"""Natural-language summaries of gold rows.

This is the piece that makes semantic search work over structured data.

Embedding a table row directly fails: `("union_metro_station", 1, 25.2, 55.3)`
has no semantic surface for a query like "which zone is Union in?" to match
against. Rendering the same row as a sentence — *"Union Metro Station is a Metro
station on the Red Metro line in fare zone 1"* — puts it in the same embedding
space as the question.

The summaries are generated by template, not by a language model. A model
writing 150 summaries would hallucinate a zone number eventually, and these
strings are retrieved as evidence, so a single invented fact would propagate
into a cited answer. Templates cannot invent.

Each summary keeps a pointer back to its row, so a citation resolves to real
data rather than to the generated prose.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import polars as pl

from backend.ingestion.arabic import normalise_arabic
from backend.services.logging import get_logger

log = get_logger(__name__)


@dataclass(slots=True)
class RowSummary:
    summary_id: str
    table: str
    row_key: str
    text_en: str
    text_ar: str | None
    source_url: str
    captured_at: str
    metadata: dict[str, str | int | float | None]


def _clean(value: object) -> str:
    return "" if value is None else str(value).strip()


def station_summaries(frame: pl.DataFrame) -> list[RowSummary]:
    summaries: list[RowSummary] = []
    for row in frame.iter_rows(named=True):
        name_en = _clean(row.get("station_name_en"))
        name_ar = _clean(row.get("station_name_ar"))
        if not (name_en or name_ar):
            continue

        mode = _clean(row.get("mode")) or "transport"
        line = _clean(row.get("line_name"))
        zone = row.get("zone_id")
        lat, lon = row.get("latitude"), row.get("longitude")

        parts = [f"{name_en or name_ar} is a {mode} station in Dubai"]
        if line:
            parts.append(f"on the {line}")
        if zone is not None:
            parts.append(f"in fare zone {int(zone)}")
        sentence = " ".join(parts) + "."

        if name_ar and name_en:
            sentence += f" Its name in Arabic is {name_ar}."
        if lat is not None and lon is not None:
            sentence += f" It is located at latitude {lat:.5f}, longitude {lon:.5f}."
        if zone is not None:
            sentence += (
                f" A journey starting or ending here is charged from fare zone {int(zone)}; "
                "the nol fare depends on how many zones the whole journey crosses."
            )
        if opened := _clean(row.get("opened_on")):
            sentence += f" It opened on {opened[:10]}."

        arabic = None
        if name_ar:
            arabic_parts = [f"{name_ar} هي محطة {mode} في دبي"]
            if line:
                arabic_parts.append(f"على {line}")
            if zone is not None:
                arabic_parts.append(f"في منطقة الأجرة {int(zone)}")
            arabic = " ".join(arabic_parts) + "."
            if name_en:
                arabic += f" اسمها بالإنجليزية {name_en}."

        summaries.append(
            RowSummary(
                summary_id=f"dim_station:{row['station_key']}",
                table="dim_station",
                row_key=str(row["station_key"]),
                text_en=sentence,
                text_ar=arabic,
                source_url=_clean(row.get("source_url")),
                captured_at=_clean(row.get("captured_at")),
                metadata={
                    "mode": mode,
                    "zone_id": int(zone) if zone is not None else None,
                    "line_name": line or None,
                    "latitude": lat,
                    "longitude": lon,
                    "station_name_en": name_en or None,
                    "station_name_ar_norm": normalise_arabic(name_ar) if name_ar else None,
                },
            )
        )
    return summaries


def route_summaries(frame: pl.DataFrame) -> list[RowSummary]:
    summaries: list[RowSummary] = []
    for row in frame.iter_rows(named=True):
        number = _clean(row.get("route_number"))
        if not number:
            continue
        mode = _clean(row.get("mode")) or "transport"
        origin = _clean(row.get("origin_en"))
        destination = _clean(row.get("destination_en"))
        stops = row.get("stop_count")
        length = row.get("route_length_km")
        route_type = _clean(row.get("route_type"))

        sentence = f"Route {number} is a Dubai {mode.lower()} route"
        if route_type:
            sentence += f" of type {route_type}"
        if origin and destination:
            sentence += f" running between {origin} and {destination}"
        sentence += "."
        if stops:
            sentence += f" It serves {int(stops)} stops."
        if length:
            sentence += f" Its recorded length is {length:.1f} km."

        summaries.append(
            RowSummary(
                summary_id=f"dim_route:{row['route_key']}",
                table="dim_route",
                row_key=str(row["route_key"]),
                text_en=sentence,
                text_ar=None,
                source_url=_clean(row.get("source_url")),
                captured_at=_clean(row.get("captured_at")),
                metadata={
                    "mode": mode,
                    "route_number": number,
                    "stop_count": int(stops) if stops else None,
                },
            )
        )
    return summaries


def ridership_summaries(frame: pl.DataFrame, *, top_n: int = 120) -> list[RowSummary]:
    """Summaries of aggregate ridership, not of every fact row.

    Embedding 7,187 individual month-station rows would flood the index with
    near-identical sentences and crowd out everything else. Aggregating per
    entity gives one informative summary each, which is what a question like
    "which metro station is busiest?" actually needs.

    Rows flagged as non-comparable are excluded from the aggregate and the
    exclusion is stated in the summary text, so a retrieved summary can never
    imply a completeness the underlying data does not have.
    """
    if frame.is_empty():
        return []

    comparable = (
        frame.filter(~pl.col("scale_anomaly")) if "scale_anomaly" in frame.columns else frame
    )
    if comparable.is_empty():
        return []

    aggregated = (
        comparable.group_by(["mode", "grain", "entity_name"])
        .agg(
            pl.col("trips").sum().alias("total_trips"),
            pl.col("trips").mean().alias("mean_trips"),
            pl.col("date_key").min().alias("first_period"),
            pl.col("date_key").max().alias("last_period"),
            pl.len().alias("periods"),
            pl.col("source_url").first().alias("source_url"),
            pl.col("captured_at").first().alias("captured_at"),
        )
        .sort("total_trips", descending=True)
        .head(top_n)
    )

    excluded = (
        int(frame.filter(pl.col("scale_anomaly")).height)
        if "scale_anomaly" in frame.columns
        else 0
    )

    summaries: list[RowSummary] = []
    for rank, row in enumerate(aggregated.iter_rows(named=True), 1):
        entity = _clean(row["entity_name"])
        mode, grain = _clean(row["mode"]), _clean(row["grain"])
        first, last = _clean(row["first_period"]), _clean(row["last_period"])

        sentence = (
            f"{entity} is a Dubai {mode} {grain} with {row['total_trips']:,.0f} total "
            f"recorded passenger trips across {row['periods']} monthly periods "
            f"from {first[:4]}-{first[4:]} to {last[:4]}-{last[4:]}, "
            f"averaging {row['mean_trips']:,.0f} trips per month. "
            f"It ranks number {rank} by total recorded trips among Dubai {mode} {grain}s "
            "in the data Masar holds."
        )
        if excluded:
            sentence += (
                " Periods whose reported magnitude was inconsistent with the rest of the "
                "series were excluded from this total, so it covers comparable periods only."
            )

        summaries.append(
            RowSummary(
                summary_id=f"fact_ridership:{mode}:{row['entity_name']}",
                table="fact_ridership_monthly",
                row_key=f"{mode}|{grain}|{entity}",
                text_en=sentence,
                text_ar=None,
                source_url=_clean(row["source_url"]),
                captured_at=_clean(row["captured_at"]),
                metadata={
                    "mode": mode,
                    "grain": grain,
                    "rank": rank,
                    "total_trips": float(row["total_trips"]),
                },
            )
        )
    return summaries


def modal_split_summaries(frame: pl.DataFrame) -> list[RowSummary]:
    if frame.is_empty():
        return []
    summaries: list[RowSummary] = []
    for (date_key,), group in frame.group_by(["date_key"], maintain_order=True):
        rows = group.sort("trips", descending=True)
        total = float(rows.get_column("trips").sum())
        if total <= 0:
            continue
        breakdown = ", ".join(
            f"{_clean(r['transport_type'])} {r['trips']:,.0f} trips "
            f"({r['trips'] / total:.0%})"
            for r in rows.iter_rows(named=True)
        )
        key = str(date_key)
        sentence = (
            f"In {key[:4]}-{key[4:]}, Dubai public transport recorded {total:,.0f} trips "
            f"in total across modes: {breakdown}."
        )
        first = rows.row(0, named=True)
        summaries.append(
            RowSummary(
                summary_id=f"modal_split:{key}",
                table="fact_modal_split_monthly",
                row_key=key,
                text_en=sentence,
                text_ar=None,
                source_url=_clean(first.get("source_url")),
                captured_at=_clean(first.get("captured_at")),
                metadata={"date_key": key, "total_trips": total},
            )
        )
    return summaries


def salik_summaries(frame: pl.DataFrame) -> list[RowSummary]:
    if frame.is_empty():
        return []
    rows = frame.sort("date_key")
    first, last = rows.row(0, named=True), rows.row(-1, named=True)
    fares = sorted({float(f) for f in rows.get_column("fare_aed").to_list()})
    sentence = (
        f"The Salik road toll recorded in Masar's data is "
        f"AED {fares[0]:.2f} per gate crossing"
        + (f" (values range AED {fares[0]:.2f} to AED {fares[-1]:.2f})" if len(fares) > 1 else "")
        + f", covering {rows.height} monthly periods from "
        f"{_clean(first['date_key'])[:4]} to {_clean(last['date_key'])[:4]}. "
        "RTA later introduced variable peak pricing, which is not present in this data, "
        "so a present-day peak-hour crossing costs more than this rate."
    )
    return [
        RowSummary(
            summary_id="dim_salik_tariff:all",
            table="dim_salik_tariff",
            row_key="all",
            text_en=sentence,
            text_ar=None,
            source_url=_clean(last.get("source_url")),
            captured_at=_clean(last.get("captured_at")),
            metadata={"fare_aed": fares[-1]},
        )
    ]


def build_all(gold_dir: Path) -> list[RowSummary]:
    def load(name: str) -> pl.DataFrame:
        path = gold_dir / f"{name}.parquet"
        return pl.read_parquet(path) if path.exists() else pl.DataFrame()

    summaries: list[RowSummary] = []
    summaries += station_summaries(load("dim_station"))
    summaries += route_summaries(load("dim_route"))
    summaries += ridership_summaries(load("fact_ridership_monthly"))
    summaries += modal_split_summaries(load("fact_modal_split_monthly"))
    summaries += salik_summaries(load("dim_salik_tariff"))

    log.info("row_summaries.built", count=len(summaries))
    return summaries
