import type { Metadata, Viewport } from "next";
import { Inter, IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import { ThemeScript } from "@/components/ThemeScript";
import { Nav } from "@/components/Nav";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const arabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-arabic",
  display: "swap",
});

const DESCRIPTION =
  "Agentic RAG over Dubai RTA open data. A 14-agent corrective loop that plans, gathers evidence, grades it, and re-plans — every claim cited. Independent academic project, not affiliated with or endorsed by the Roads and Transport Authority.";

export const metadata: Metadata = {
  // Absolute URLs for OG/Twitter tags are resolved against this base.
  metadataBase: new URL("https://masar-ai-xi.vercel.app"),
  title: {
    default: "Masar AI — Dubai Mobility Decision Intelligence",
    template: "%s · Masar AI",
  },
  description: DESCRIPTION,
  applicationName: "Masar AI",
  authors: [{ name: "Krishna Mathur" }],
  keywords: [
    "Dubai RTA",
    "agentic RAG",
    "public transport",
    "LangGraph",
    "corrective RAG",
    "bilingual AI",
  ],
  openGraph: {
    type: "website",
    siteName: "Masar AI",
    url: "https://masar-ai-xi.vercel.app",
    title: "Masar AI — Dubai Mobility Decision Intelligence",
    description: DESCRIPTION,
    // The image is generated by app/opengraph-image.tsx (Next convention).
  },
  twitter: {
    card: "summary_large_image",
    title: "Masar AI — Dubai Mobility Decision Intelligence",
    description: DESCRIPTION,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f6f2ea" },
    { media: "(prefers-color-scheme: dark)", color: "#100f0d" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className={`${inter.variable} ${arabic.variable}`}>
      <head>
        {/* Applies the stored theme before first paint so there is no flash. */}
        <ThemeScript />
      </head>
      {/* h-dvh (not min-h-screen) so the app is viewport-locked and each route
          scrolls internally — otherwise a tall page grows the document and
          strands the chat composer far below the fold on mobile. */}
      <body className="h-dvh flex flex-col overflow-hidden">
        <Nav />
        <div className="flex-1 flex flex-col min-h-0">{children}</div>
        <footer className="shrink-0 border-t border-[var(--border)] px-4 py-3 text-[0.7rem] leading-relaxed text-[var(--text-faint)]">
          <div className="mx-auto max-w-[1600px]">
            <strong className="text-[var(--text-muted)]">Masar AI is an independent academic project.</strong>{" "}
            It is not affiliated with, endorsed by, or connected to the Roads and Transport Authority.
            It uses publicly available open data published by RTA via Dubai Pulse, recovered from
            public Internet Archive snapshots. Live operational data is not publicly available and is
            not simulated as live.
          </div>
        </footer>
      </body>
    </html>
  );
}
